server:
  port: 8082
  ssl:
    key-store-type: PKCS12
    key-store: KP/bank2-service/src/main/resources/bank2.p12
    key-store-password: kp2020
    key-alias: bank2
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank2_service?useSSL=false&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update #modify StartupDataAdder as necessary
  application:
    name: bank2-service

database:
  encryption:
    key: T8n2jvplwDlXTqUBOJW1GttdYOHkpPtZ

api:
  frontend: https://localhost:4203
  pcc: https://localhost:8083/api