server:
  port: 0
  ssl:
    key-store-type: PKCS12
    key-store: KP/kp-service/src/main/resources/kpBackend.p12
    key-store-password: kp2020
    key-alias: kpbackend
    trust-store: KP/kp-service/src/main/resources/kpBackend_truststore.p12
    trust-store-password: kp2020
    trust-store-type: PKCS12
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/koncentrator_placanja?useSSL=false&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      host: localhost
      port: 27017
      database: LogsKP
  application:
    name: kp-service

eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.int}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
