package lu.ftn.model.entity;

public enum BookStatus {
    CREATED,
    PASSED_INITIAL_REVIEW,
    WAITING_FULL_MANUSCRIPT,
    UPLOADED_FULL_MANUSCRIPT,
    NOT_PLAGIARISM,
    DECIDE_ON_BETAREADERS,
    DECIDED_ON_BETAREADERS,
    SENT_TO_BETA_READERS,
    FINISHED_BETA_READING,
    RE_UPLOADED_MANUSCRIPT,
    SENT_TO_LECTOR,
    LECTOR_ASKS_FOR_CHANGES,
    LECTOR_APPROVES,
    EDITOR_ASKS_FOR_CHANGES,
    WAITING_FINAL_CHANGES,
    PUBLISHED,
    REJECTED,
    IN_REVIEW,
    AVAILABLE,
    TAKEDOWN_PLAGIARISM
}
