server:
  port: 8761
  ssl:
    key-store-type: PKCS12
    key-store: KP/discovery-service/src/main/resources/kpDiscovery.p12
    key-store-password: kp2020
    key-alias: kpdiscovery
    enabled: true
    trust-store: KP/discovery-service/src/main/resources/kpDiscovery_truststore.p12
    trust-store-password: kp2020
    trust-store-type: PKCS12

spring:
  application:
    name: discovery-service

eureka:
  instance:
    hostname: localhost
    securePort: ${server.port}
    securePortEnabled: true
    nonSecurePortEnabled: false
    homePageUrl: https://${eureka.instance.hostname}:${server.port}/
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/admin/info
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false