server:
  port: 0
  ssl:
    key-store-type: PKCS12
    key-store: KP/bitcoin-payment-service/src/main/resources/kpBitcoin.p12
    key-store-password: kp2020
    key-alias: kpbitcoin
    enabled: true

database:
  encryption:
    key: PmgUr9TwuwegGubXtReQ6P8d5EZnIriY

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bitcoin_payment_service?useSSL=false&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: bitcoin-payment-service

eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.int}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}